<?php $this->extend('layouts/admin.phtml'); ?>

<?php $this->startSection('content'); ?>
<div class="components new container-fluid">
    <h1 class="page-header"><?=t('new_component')?></h1>

    <form action="<?=baseUrl('/admin/components/new')?>" method="post" class="form-horizontal">
        <?=view('admin/components/_form.phtml', ['component' => $component])?>
        <div class="text-center">
            <button type="submit" class="btn btn-success"><?=t('create')?></button>
        </div>
    </form>
</div>
<?php $this->endSection(); ?>
