<?php $this->extend('layouts/admin.phtml'); ?>

<?php $this->startSection('content'); ?>
<div class="milestones container-fluid">
    <div class="pull-right">
        <a href="<?=baseUrl('/admin/milestones/new')?>" class="btn btn-sm btn-success">
            <span class="fa fa-plus"></span> <?=t('new_milestone')?>
        </a>
    </div>

    <h1 class="page-header"><?=t('milestones')?></h1>

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th><?=t('name')?></th>
                <th><?=t('project')?></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($milestones as $milestone) : ?>
            <tr>
                <td><a href="<?=baseUrl("/admin/milestones/{$milestone['id']}/edit")?>"><?=$milestone['name']?></a></td>
                <td><?=$milestone['project_name']?></td>
                <td>
                    <div class="text-right">
                        <a href="<?=baseUrl("/admin/milestones/{$milestone['id']}/edit")?>" class="btn btn-xs btn-warning" title="<?=t('edit')?>">
                            <span class="fa fa-pencil"></span> <span class="sr-only"><?=t('edit')?></span>
                        </a>

                        <a href="<?=baseUrl("/admin/milestones/{$milestone['id']}/delete")?>" class="btn btn-xs btn-danger" title="<?=t('delete')?>" data-confirm="<?=t('confirm.delete_x', [$milestone['name']])?>">
                            <span class="fa fa-trash"></span> <span class="sr-only"><?=t('delete')?></span>
                        </a>
                    </div>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
<?php $this->endSection(); ?>
