<div class="milestones new container-fluid">
    <h1 class="page-header"><?=t('new_milestone')?></h1>

    <form action="<?=baseUrl('/admin/milestones/new')?>" method="post" class="form-horizontal">
        <?=view('admin/milestones/_form.phtml', ['milestone' => $milestone])?>
        <div class="text-center">
            <button type="submit" class="btn btn-success"><?=t('create_milestone')?></button>
        </div>
    </form>
</div>
