<?php $this->extend('layouts/admin.phtml'); ?>

<?php $this->startSection('content'); ?>
<div class="users edit container-fluid">
    <h1 class="page-header"><?=t('edit_user')?></h1>

    <form action="<?=baseUrl("/admin/users/{$user['id']}/edit")?>" method="post" class="form-horizontal">
        <?=view('admin/users/_form.phtml', ['user' => $user])?>
        <div class="text-center">
            <button type="submit" class="btn btn-success"><?=t('save')?></button>
        </div>
    </form>
</div>
<?php $this->endSection(); ?>
