<?php $this->extend('layouts/admin.phtml'); ?>

<?php $this->startSection('content'); ?>
<div class="users container-fluid">
    <div class="pull-right">
        <a href="<?=baseUrl('/admin/users/new')?>" class="btn btn-sm btn-success">
            <span class="fa fa-plus"></span> <?=t('new_user')?>
        </a>
    </div>

    <h1 class="page-header"><?=t('users')?></h1>

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th><?=t('username')?></th>
                <th><?=t('group')?></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($users as $user) : ?>
            <tr>
                <td><a href="<?=baseUrl("/admin/users/{$user['id']}/edit")?>"><?=$user['username']?></a></td>
                <td><?=$user['group_name']?></td>
                <td>
                    <div class="text-right">
                        <a href="<?=baseUrl("/admin/users/{$user['id']}/edit")?>" class="btn btn-xs btn-warning" title="<?=t('edit')?>">
                            <span class="fa fa-pencil"></span> <span class="sr-only"><?=t('edit')?></span>
                        </a>

                        <a href="<?=baseUrl("/admin/users/{$user['id']}/delete")?>" class="btn btn-xs btn-danger" title="<?=t('delete')?>" data-confirm="<?=t('confirm.delete_x', [$user['username']])?>">
                            <span class="fa fa-trash"></span> <span class="sr-only"><?=t('delete')?></span>
                        </a>
                    </div>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
<?php $this->endSection(); ?>
