<div class="statuses edit container-fluid">
    <h1 class="page-header"><?=t('edit_status')?></h1>

    <form action="<?=baseUrl("/admin/statuses/{$status['id']}/edit")?>" method="post" class="form-horizontal">
        <?=view('admin/statuses/_form.phtml', ['status' => $status])?>
        <div class="text-center">
            <button status="submit" class="btn btn-success"><?=t('save')?></button>
        </div>
    </form>
</div>
