<div class="statuses container-fluid">
    <div class="pull-right">
        <a href="<?=baseUrl('/admin/statuses/new')?>" class="btn btn-sm btn-success">
            <span class="fa fa-plus"></span> <?=t('new_status')?>
        </a>
    </div>

    <h1 class="page-header"><?=t('ticket_statuses')?></h1>

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th><?=t('name')?></th>
                <th><?=t('status')?></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($statuses as $status) : ?>
            <tr>
                <td><a href="<?=baseUrl("/admin/statuses/{$status['id']}/edit")?>"><?=$status['name']?></a></td>
                <td><?=t($status['status'] == '1' ? 'open' : 'closed')?></td>
                <td>
                    <div class="text-right">
                        <a href="<?=baseUrl("/admin/statuses/{$status['id']}/edit")?>" class="btn btn-xs btn-warning" title="<?=t('edit')?>">
                            <span class="fa fa-pencil"></span> <span class="sr-only"><?=t('edit')?></span>
                        </a>

                        <a href="<?=baseUrl("/admin/statuses/{$status['id']}/delete")?>" class="btn btn-xs btn-danger" title="<?=t('delete')?>" data-confirm="<?=t('confirm.delete_x', [$status['name']])?>">
                            <span class="fa fa-trash"></span> <span class="sr-only"><?=t('delete')?></span>
                        </a>
                    </div>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
