<?php $this->extend('layouts/admin.phtml'); ?>

<?php $this->startSection('content'); ?>
<div class="statuses new container-fluid">
    <h1 class="page-header"><?=t('new_status')?></h1>

    <form action="<?=baseUrl('/admin/statuses/new')?>" method="post" class="form-horizontal">
        <?=view('admin/statuses/_form.phtml', ['status' => $status])?>
        <div class="text-center">
            <button status="submit" class="btn btn-success"><?=t('create')?></button>
        </div>
    </form>
</div>
<?php $this->endSection(); ?>
