<?php $this->extend('layouts/admin.phtml'); ?>

<?php $this->startSection('content'); ?>
<div class="types container-fluid">
    <div class="pull-right">
        <a href="<?=baseUrl('/admin/types/new')?>" class="btn btn-sm btn-success">
            <span class="fa fa-plus"></span> <?=t('new_type')?>
        </a>
    </div>

    <h1 class="page-header"><?=t('ticket_types')?></h1>

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th><?=t('name')?></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($types as $type) : ?>
            <tr>
                <td><a href="<?=baseUrl("/admin/types/{$type['id']}/edit")?>"><?=$type['name']?></a></td>
                <td>
                    <div class="text-right">
                        <a href="<?=baseUrl("/admin/types/{$type['id']}/edit")?>" class="btn btn-xs btn-warning" title="<?=t('edit')?>">
                            <span class="fa fa-pencil"></span> <span class="sr-only"><?=t('edit')?></span>
                        </a>

                        <a href="<?=baseUrl("/admin/types/{$type['id']}/delete")?>" class="btn btn-xs btn-danger" title="<?=t('delete')?>" data-confirm="<?=t('confirm.delete_x', [$type['name']])?>">
                            <span class="fa fa-trash"></span> <span class="sr-only"><?=t('delete')?></span>
                        </a>
                    </div>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
<?php $this->endSection(); ?>
