<div class="types new container-fluid">
    <h1 class="page-header"><?=t('new_type')?></h1>

    <form action="<?=baseUrl('/admin/types/new')?>" method="post" class="form-horizontal">
        <?=view('admin/types/_form.phtml', ['type' => $type])?>
        <div class="text-center">
            <button type="submit" class="btn btn-success"><?=t('create')?></button>
        </div>
    </form>
</div>
