<div class="tickets container">
    <h1 class="page-header"><?=t('tickets')?></h1>

    <table class="table table-bordered table-striped table-hover">
        <thead>
            <th><?=t('id')?></th>
            <th><?=t('summary')?></th>
        </thead>
        <tbody>
        <?php foreach ($tickets as $ticket) : ?>
            <tr>
                <td><?=$ticket['ticket_id']?></td>
                <td><a href="<?=projectUrl('/tickets/' . $ticket['ticket_id'])?>"><?=e($ticket['summary'])?></a></td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
