<?php $this->extend('layouts/default.phtml'); ?>

<?php $this->startSection('content'); ?>
<div class="projects content container-fluid">
    <h1 class="page-header"><?=t('projects')?></h1>

    <ul>
    <?php foreach ($projects as $project) : ?>
        <li>
            <h2 class="project-name"><a href="<?=baseUrl($project['slug'])?>"><?=$project['name']?></a></h2>
            <?=markdown($project['description'])?>
        </li>
    <?php endforeach ?>
    </ul>
</div>
<?php $this->endSection(); ?>
