<div class="sidebar-wrapper sidebar-expanded">
    <a href="<?=baseUrl('/admin')?>" class="sidebar-brand" title="<?=t('dashboard')?>" data-placement="bottom">
        <span class="product-name">Traq Lite</span>
        <span class="product-version">v<?=Traq\Kernel::VERSION?></span>
    </a>

    <ul class="nav nav-sidebar">
        <li>
            <a href="<?=baseUrl()?>"><span class="fa fa-fw fa-home"></span> <?=t('view_site')?></a>
        </li>
        <li class="divider"></li>
        <li class="<?=iif(Request::matches('/admin/settings.*'), 'active')?>">
            <a href="<?=baseUrl('/admin/settings')?>"><span class="fa fa-fw fa-cogs"></span> <?=t('settings')?></a>
        </li>
        <li class="<?=iif(Request::matches('/admin/projects.*'), 'active')?>">
            <a href="<?=baseUrl('/admin/projects')?>"><span class="fa fa-fw fa-folder"></span> <?=t('projects')?></a>
        </li>
        <li class="<?=iif(Request::matches('/admin/types.*'), 'active')?>">
            <a href="<?=baseUrl('/admin/types')?>"><span class="fa fa-fw fa-bookmark"></span> <?=t('ticket_types')?></a>
        </li>
        <li class="<?=iif(Request::matches('/admin/statuses.*'), 'active')?>">
            <a href="<?=baseUrl('/admin/statuses')?>"><span class="fa fa-fw fa-question"></span> <?=t('ticket_statuses')?></a>
        </li>
        <li class="<?=iif(Request::matches('/admin/milestones.*'), 'active')?>">
            <a href="<?=baseUrl('/admin/milestones')?>"><span class="fa fa-fw fa-map-signs"></span> <?=t('milestones')?></a>
        </li>
        <li class="<?=iif(Request::matches('/admin/components.*'), 'active')?>">
            <a href="<?=baseUrl('/admin/components')?>"><span class="fa fa-fw fa-puzzle-piece"></span> <?=t('components')?></a>
        </li>
        <li class="<?=iif(Request::matches('/admin/users.*'), 'active')?>">
            <a href="<?=baseUrl('/admin/users')?>"><span class="fa fa-fw fa-venus-mars"></span> <?=t('users')?></a>
        </li>
        <li class="<?=iif(Request::matches('/admin/groups.*'), 'active')?>">
            <a href="<?=baseUrl('/admin/groups')?>"><span class="fa fa-fw fa-users"></span> <?=t('groups')?></a>
        </li>
    </ul>
</div>
