<div class="projects edit container-fluid">
    <h1 class="page-header"><?=t('edit_project')?></h1>

    <form action="<?=baseUrl("/admin/projects/{$project['id']}/edit")?>" method="post" class="form-horizontal">
        <?=view('admin/projects/_form.phtml', ['project' => $project])?>
        <div class="text-center">
            <button type="submit" class="btn btn-success"><?=t('save')?></button>
        </div>
    </form>
</div>
