<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>

    <link rel="stylesheet" href="<?=baseUrl('/assets/css/traq.css')?>">
    <link rel="stylesheet" href="<?=baseUrl('/assets/css/admin.css')?>">

    <script src="<?=baseUrl('assets/js/js.js')?>"></script>
    <script src="<?=baseUrl('assets/js/common.js')?>"></script>
</head>
<body>
    <div class="page-with-sidebar">
        <?=view('layouts/admin/_sidebar.phtml')?>
        <main>
            <?=$content?>
        </main>
        <footer id="footer">
            <?php if ($_ENV['environment'] === 'development') : ?>
            <div class="text-muted pull-right">
                <?=round((microtime(true) - START_TIME), 2); ?>s, <?php echo round((memory_get_peak_usage() - START_MEM) / pow(1024, 2), 3)?>mb
            </div>
            <?php endif ?>

            Powered by Traq Lite &copy; <?=date('Y')?>
        </footer>
    </div>
</body>
</html>
