<div class="registration container">
    <h1 class="page-header"><?=t('register')?></h1>

    <form action="<?=baseUrl('/register')?>" method="post" class="form-tabular col-span-6 col-offset-3">
        <div class="form-group <?=iif($user->hasError('username'), 'has-error')?>">
            <label for="username" class="control-label col-span-3"><?=t('username')?></label>
            <div class="col col-span-9">
                <input type="text" name="username" id="username" class="form-control" value="<?=$user['username']?>">
                <?php if ($user->hasError('username')) : ?>
                    <div class="help-block"><?=errorMessageFor($user, 'username')?></div>
                <?php endif ?>
            </div>
        </div>

        <div class="form-group <?=iif($user->hasError('password'), 'has-error')?>">
            <label for="password" class="control-label col-span-3"><?=t('password')?></label>
            <div class="col col-span-9">
                <input type="password" name="password" id="password" class="form-control">
                <?php if ($user->hasError('password')) : ?>
                    <div class="help-block"><?=errorMessageFor($user, 'password')?></div>
                <?php endif ?>
            </div>
        </div>

        <div class="form-group <?=iif($user->hasError('email'), 'has-error')?>">
            <label for="email" class="control-label col-span-3"><?=t('email')?></label>
            <div class="col col-span-9">
                <input type="email" name="email" id="email" class="form-control" value="<?=$user['email']?>">
                <?php if ($user->hasError('email')) : ?>
                    <div class="help-block"><?=errorMessageFor($user, 'email')?></div>
                <?php endif ?>
            </div>
        </div>

        <div class="form-actions text-center">
            <button class="btn btn-success"><?=t('create_account')?></button>
        </div>
    </form>
</div>
